apiVersion: apps/v1
kind: Deployment
metadata:
  name: foodie
spec:
  selector:
    matchLabels:
      app: foodie
  template:
    metadata:
      labels:
        app: foodie
    spec:
      containers:
        - name: foodie
          image: nginx
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /food/
              name: specialofday
            - mountPath: /newvol
              name: reviewvol
      volumes:
        - name: specialofday
          secret:
            secretName: specialofday
        - name: reviewvol
          persistentVolumeClaim:
            claimName: reviewvol
