apiVersion: v1
kind: PersistentVolume
metadata:
  name: reviewvol
spec:
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /opt/sfw
    server: 192.168.64.11
