apiVersion: v1
kind: Service
metadata:
  name: webserver-nodeport
spec:
  type: NodePort
  selector:
    app: my-httpd
  sessionAffinity: None
  ports:
    - port: 80
      targetPort: 80
      nodePort: 32080
