apiVersion: v1
kind: Pod
metadata:
  name: basicpod
  labels:
    type: webserver
spec:
  containers:
    - name: webcont
      image: nginx
      resources:
        limits:
          memory: "128Mi"
          cpu: "200m"
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: /var/log/nginx/
          name: weblog-pv-storage
    - name: fdlogger
      image: fluent/fluentd
      resources:
        limits:
          memory: "128Mi"
          cpu: "200m"
      env:
        - name: FLUENTD_OPT
          value: -c /etc/fluentd-config/fluentd.conf
      volumeMounts:
        - mountPath: /var/log
          name: weblog-pv-storage
        - mountPath: /etc/fluentd-config
          name: log-config
  volumes:
    - name: weblog-pv-storage
      persistentVolumeClaim:
        claimName: weblog
    - name: log-config
      configMap:
        name: fluentd-config
