apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: securityaccount-rb
subjects:
  - kind: ServiceAccount
    name: securityaccount
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pod-crd-cr
